services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - ./allure-results:/usr/workspace/allure-results
    command: >
      pytest -sv --alluredir=/usr/workspace/allure-results
    working_dir: /usr/workspace
    environment:
      - SITE_EMAIL=${SITE_EMAIL}
      - SITE_PASSWORD=${SITE_PASSWORD}
