version: "3.8"

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - SITE_EMAIL=${SITE_EMAIL}
      - SITE_PASSWORD=${SITE_PASSWORD}
