name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          SITE_EMAIL: ${{secrets.SITE_EMAIL}}
          SITE_PASSWORD: ${{secrets.SITE_PASSWORD}}
        run: |
          docker compose up --exit-code-from regression || true

      - name: Install Allure CLI
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget default-jre
          ALLURE_VERSION=2.29.0
          wget -q https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip -O /tmp/allure.zip
          sudo unzip -q /tmp/allure.zip -d /opt
          sudo ln -sf /opt/allure-${ALLURE_VERSION}/bin/allure /usr/local/bin/allure
          allure --version

      - name: Copy history from gh-pages to allure-results
        if: always()
        run: |
          mkdir -p allure-results/history
          cp -R gh-pages/history/* allure-results/history/ || true

      - name: Generate Allure report
        if: always()
        run: |
          rm -rf allure-report
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{secrets.CI_TOKEN}}
          branch: gh-pages
          folder: allure-report
          clean: true
