name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        env:
          SITE_EMAIL: ${{secrets.SITE_EMAIL}}
          SITE_PASSWORD: ${{secrets.SITE_PASSWORD}}
        run: |
          docker compose up --exit-code-from regression || true

      - name: Install Allure
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure report
        if: always()
        run: |
          sudo docker compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{secrets.CI_TOKEN}}
          branch: gh-pages
          folder: allure-report
          clean: true
